project:
  type: website

website:
  title: "Song Billboard Analysis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bigchayanont
format:
  html:
    theme: minty
    css: styles.css



